export const SERVICES = [
  { code: "NOVA", name: "Compute", copy: "Virtual machines, key pairs, flavors and resilient workload scheduling." },
  { code: "NEUTRON", name: "Networking", copy: "Private networks, routers, floating IPs, security groups and VPN-ready topology." },
  { code: "CINDER", name: "Block storage", copy: "Persistent volumes and snapshots designed to move with your workloads." },
  { code: "SWIFT", name: "Object storage", copy: "S3-style durable object storage for assets, archives and backups." },
  { code: "MANILA", name: "Shared filesystems", copy: "Managed file shares with protocol-aware access and tenant controls." },
  { code: "GLANCE", name: "Image service", copy: "Curated operating-system images and your own reusable machine templates." },
  { code: "KEYSTONE", name: "Identity", copy: "Projects, roles and policy-backed isolation across every tenant." },
  { code: "HEAT", name: "Orchestration", copy: "Repeatable infrastructure stacks expressed as versionable templates." },
  { code: "OCTAVIA", name: "Load balancing", copy: "Managed application delivery across healthy backend instances." },
  { code: "DESIGNATE", name: "DNS", copy: "Programmable zones and records integrated with cloud resources." },
  { code: "BARBICAN", name: "Key management", copy: "Protected secrets, certificates and encryption material." },
  { code: "IRONIC", name: "Bare metal", copy: "Provision physical machines through the same cloud control plane." },
  { code: "HORIZON", name: "Dashboard", copy: "A native browser interface for tenants, resources and cloud operations." },
  { code: "PLACEMENT", name: "Placement", copy: "Resource inventories and allocation candidates for reliable scheduling." },
  { code: "MAGNUM", name: "Container infrastructure", copy: "Managed Kubernetes and container clusters on OpenStack resources." },
  { code: "TROVE", name: "Database service", copy: "Lifecycle management for relational and non-relational databases." },
  { code: "WATCHER", name: "Infrastructure optimisation", copy: "Workload balancing and efficiency recommendations for the cloud." },
  { code: "MASAKARI", name: "Instance high availability", copy: "Automated recovery workflows for failed compute instances." },
  { code: "ZAQAR", name: "Messaging", copy: "Multi-tenant queues and messaging for distributed applications." },
  { code: "BLAZAR", name: "Resource reservation", copy: "Advance reservations for compute hosts and tenant instances." },
  { code: "CEILOMETER", name: "Telemetry collection", copy: "Usage signals, events and measurements for cloud resources." },
  { code: "AODH", name: "Telemetry alarming", copy: "Rule-based alarms driven by collected metrics and event data." },
  { code: "CLOUDKITTY", name: "Rating", copy: "Usage rating and chargeback-ready data for cloud services." },
  { code: "CYBORG", name: "Accelerators", copy: "Lifecycle management for GPUs, FPGAs and other accelerator devices." },
] as const;
